name: Unstructured CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  CLUSTER_NAME: "unstructured-gpu-production-cluster"
  SERVICE_NAME: "unstructured-gpu-production-ecs-service"

jobs:
  CI:
    # Define the runner used in the workflow
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out repo so our workflow can access it
      - uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Create docker image and push to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 699462293159.dkr.ecr.us-east-1.amazonaws.com
          docker build -t unstructured-api-gpu .
          docker tag unstructured-api-gpu:latest 699462293159.dkr.ecr.us-east-1.amazonaws.com/unstructured-api-gpu:latest
          docker push 699462293159.dkr.ecr.us-east-1.amazonaws.com/unstructured-api-gpu:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      # Check out repo so our workflow can access it
      - uses: actions/checkout@v3

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Deploy to ECS
        run: aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
